// ── 版本配置 ──────────────────────────────────────────────────────────────
// 在这里增删你放进 data/ 文件夹的版本
export const VERSIONS = [
  { id: "cuv1", label: "和合本1", lang: "zh" },
  { id: "cuv2", label: "和合本2", lang: "zh" },
  { id: "ccb", label: "當代譯本修訂版", lang: "zh" },
  { id: "cnv", label: "新譯本", lang: "zh" },
  { id: "tcv19", label: "現代中文譯本2019", lang: "zh" },
  { id: "kjv", label: "KJV", lang: "en" },
  { id: "nrsv", label: "NRSV", lang: "en" },
];

export const DEFAULT_LEFT = "cuv1";
export const DEFAULT_RIGHT = "kjv";

// ── 书卷数据 ──────────────────────────────────────────────────────────────
export const BOOKS = [
  // 旧约
  { id: 1, file: "Gen", zh: "创世记", en: "Genesis", chapters: 50, t: "ot" },
  { id: 2, file: "Exo", zh: "出埃及记", en: "Exodus", chapters: 40, t: "ot" },
  { id: 3, file: "Lev", zh: "利未记", en: "Leviticus", chapters: 27, t: "ot" },
  { id: 4, file: "Num", zh: "民数记", en: "Numbers", chapters: 36, t: "ot" },
  {
    id: 5,
    file: "Deu",
    zh: "申命记",
    en: "Deuteronomy",
    chapters: 34,
    t: "ot",
  },
  { id: 6, file: "Jos", zh: "约书亚记", en: "Joshua", chapters: 24, t: "ot" },
  { id: 7, file: "Jug", zh: "士师记", en: "Judges", chapters: 21, t: "ot" },
  { id: 8, file: "Rut", zh: "路得记", en: "Ruth", chapters: 4, t: "ot" },
  {
    id: 9,
    file: "1Sa",
    zh: "撒母耳记上",
    en: "1 Samuel",
    chapters: 31,
    t: "ot",
  },
  {
    id: 10,
    file: "2Sa",
    zh: "撒母耳记下",
    en: "2 Samuel",
    chapters: 24,
    t: "ot",
  },
  { id: 11, file: "1Ki", zh: "列王纪上", en: "1 Kings", chapters: 22, t: "ot" },
  { id: 12, file: "2Ki", zh: "列王纪下", en: "2 Kings", chapters: 25, t: "ot" },
  {
    id: 13,
    file: "1Ch",
    zh: "历代志上",
    en: "1 Chronicles",
    chapters: 29,
    t: "ot",
  },
  {
    id: 14,
    file: "2Ch",
    zh: "历代志下",
    en: "2 Chronicles",
    chapters: 36,
    t: "ot",
  },
  { id: 15, file: "Ezr", zh: "以斯拉记", en: "Ezra", chapters: 10, t: "ot" },
  {
    id: 16,
    file: "Neh",
    zh: "尼希米记",
    en: "Nehemiah",
    chapters: 13,
    t: "ot",
  },
  { id: 17, file: "Est", zh: "以斯帖记", en: "Esther", chapters: 10, t: "ot" },
  { id: 18, file: "Job", zh: "约伯记", en: "Job", chapters: 42, t: "ot" },
  { id: 19, file: "Psa", zh: "诗篇", en: "Psalms", chapters: 150, t: "ot" },
  { id: 20, file: "Pro", zh: "箴言", en: "Proverbs", chapters: 31, t: "ot" },
  {
    id: 21,
    file: "Ecc",
    zh: "传道书",
    en: "Ecclesiastes",
    chapters: 12,
    t: "ot",
  },
  {
    id: 22,
    file: "Son",
    zh: "雅歌",
    en: "Song of Songs",
    chapters: 8,
    t: "ot",
  },
  { id: 23, file: "Isa", zh: "以赛亚书", en: "Isaiah", chapters: 66, t: "ot" },
  {
    id: 24,
    file: "Jer",
    zh: "耶利米书",
    en: "Jeremiah",
    chapters: 52,
    t: "ot",
  },
  {
    id: 25,
    file: "Lam",
    zh: "耶利米哀歌",
    en: "Lamentations",
    chapters: 5,
    t: "ot",
  },
  { id: 26, file: "Eze", zh: "以西结书", en: "Ezekiel", chapters: 48, t: "ot" },
  { id: 27, file: "Dan", zh: "但以理书", en: "Daniel", chapters: 12, t: "ot" },
  { id: 28, file: "Hos", zh: "何西阿书", en: "Hosea", chapters: 14, t: "ot" },
  { id: 29, file: "Joe", zh: "约珥书", en: "Joel", chapters: 3, t: "ot" },
  { id: 30, file: "Amo", zh: "阿摩司书", en: "Amos", chapters: 9, t: "ot" },
  {
    id: 31,
    file: "Oba",
    zh: "俄巴底亚书",
    en: "Obadiah",
    chapters: 1,
    t: "ot",
  },
  { id: 32, file: "Jon", zh: "约拿书", en: "Jonah", chapters: 4, t: "ot" },
  { id: 33, file: "Mic", zh: "弥迦书", en: "Micah", chapters: 7, t: "ot" },
  { id: 34, file: "Nah", zh: "那鸿书", en: "Nahum", chapters: 3, t: "ot" },
  { id: 35, file: "Hab", zh: "哈巴谷书", en: "Habakkuk", chapters: 3, t: "ot" },
  {
    id: 36,
    file: "Zep",
    zh: "西番雅书",
    en: "Zephaniah",
    chapters: 3,
    t: "ot",
  },
  { id: 37, file: "Hag", zh: "哈该书", en: "Haggai", chapters: 2, t: "ot" },
  {
    id: 38,
    file: "Zec",
    zh: "撒迦利亚书",
    en: "Zechariah",
    chapters: 14,
    t: "ot",
  },
  { id: 39, file: "Mal", zh: "玛拉基书", en: "Malachi", chapters: 4, t: "ot" },
  // 新约
  { id: 40, file: "Mat", zh: "马太福音", en: "Matthew", chapters: 28, t: "nt" },
  { id: 41, file: "Mak", zh: "马可福音", en: "Mark", chapters: 16, t: "nt" },
  { id: 42, file: "Luk", zh: "路加福音", en: "Luke", chapters: 24, t: "nt" },
  { id: 43, file: "Jhn", zh: "约翰福音", en: "John", chapters: 21, t: "nt" },
  { id: 44, file: "Act", zh: "使徒行传", en: "Acts", chapters: 28, t: "nt" },
  { id: 45, file: "Rom", zh: "罗马书", en: "Romans", chapters: 16, t: "nt" },
  {
    id: 46,
    file: "1Co",
    zh: "哥林多前书",
    en: "1 Corinthians",
    chapters: 16,
    t: "nt",
  },
  {
    id: 47,
    file: "2Co",
    zh: "哥林多后书",
    en: "2 Corinthians",
    chapters: 13,
    t: "nt",
  },
  {
    id: 48,
    file: "Gal",
    zh: "加拉太书",
    en: "Galatians",
    chapters: 6,
    t: "nt",
  },
  {
    id: 49,
    file: "Eph",
    zh: "以弗所书",
    en: "Ephesians",
    chapters: 6,
    t: "nt",
  },
  {
    id: 50,
    file: "Phl",
    zh: "腓立比书",
    en: "Philippians",
    chapters: 4,
    t: "nt",
  },
  {
    id: 51,
    file: "Col",
    zh: "歌罗西书",
    en: "Colossians",
    chapters: 4,
    t: "nt",
  },
  {
    id: 52,
    file: "1Ts",
    zh: "帖撒罗尼迦前书",
    en: "1 Thessalonians",
    chapters: 5,
    t: "nt",
  },
  {
    id: 53,
    file: "2Ts",
    zh: "帖撒罗尼迦后书",
    en: "2 Thessalonians",
    chapters: 3,
    t: "nt",
  },
  {
    id: 54,
    file: "1Ti",
    zh: "提摩太前书",
    en: "1 Timothy",
    chapters: 6,
    t: "nt",
  },
  {
    id: 55,
    file: "2Ti",
    zh: "提摩太后书",
    en: "2 Timothy",
    chapters: 4,
    t: "nt",
  },
  { id: 56, file: "Tit", zh: "提多书", en: "Titus", chapters: 3, t: "nt" },
  { id: 57, file: "Phm", zh: "腓利门书", en: "Philemon", chapters: 1, t: "nt" },
  { id: 58, file: "Heb", zh: "希伯来书", en: "Hebrews", chapters: 13, t: "nt" },
  { id: 59, file: "Jas", zh: "雅各书", en: "James", chapters: 5, t: "nt" },
  { id: 60, file: "1Pe", zh: "彼得前书", en: "1 Peter", chapters: 5, t: "nt" },
  { id: 61, file: "2Pe", zh: "彼得后书", en: "2 Peter", chapters: 3, t: "nt" },
  { id: 62, file: "1Jn", zh: "约翰一书", en: "1 John", chapters: 5, t: "nt" },
  { id: 63, file: "2Jn", zh: "约翰二书", en: "2 John", chapters: 1, t: "nt" },
  { id: 64, file: "3Jn", zh: "约翰三书", en: "3 John", chapters: 1, t: "nt" },
  { id: 65, file: "Jud", zh: "犹大书", en: "Jude", chapters: 1, t: "nt" },
  {
    id: 66,
    file: "Rev",
    zh: "启示录",
    en: "Revelation",
    chapters: 22,
    t: "nt",
  },
];
